apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-kafka
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ template "kafka.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  init.js: |-
{{ .Files.Get "configs/init.js" | indent 4}}