apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "redis.fullname" . }}-configuration
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
{{- if (.Files.Glob "configs/redis.conf") }}
{{ (.Files.Glob "configs/redis.conf").AsConfig | indent 2 }}
{{- end }}
